apiVersion: v1
kind: Secret
metadata:
    name: discord-template-notifier-secret
stringData:
    config.toml: ENC[AES256_GCM,data:4FGSWxFMf8Aucnt7GpX3YO0KbDo7zwO2BZFOqWWN/Y5teYUx+H3UfWHBhJ/GgBMsgABqZufkirmeMdExstj0dxJoheLnP5xabMDEoThs6/rD+SfCN04D+N7CQOeNXZKOfak6aOE7pJLnipxLZshVogMptChQxk/9K/Js4PDa7DIRDQBpVGmba3RPLsPghHtxX/AqOt06EdeqYQYWGgCaxZPED0tR9RNQD5vpMTwZQzj3G9tRxfX4YwQDewwb3Gy+OG5Ggb8GVbQ2VRE4V3i+2sZmWH906oGQTmhjmkjbx7qiCEmnwExgppPpkxnC1y66i8GKv9IxUkYCT0BnAJQp/3XySES7nN3ULRVRb7wgxdjhA4gOx/0hUGHkGGVCZhrupA==,iv:I6pxoZzMrZZmK4nTxUs1q7JWBrhuIuQzrfbaozp94hM=,tag:0ONoNhJMP65y/bYVOgEIjw==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xet7mguda7d2gt4f6re7nsv4cdr7tmqeh4lvfyhxeg66sjtghv2q9xd44n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYaVBVV0FiYmpGSUMzMWNF
            RjVaRzRpb3h4RDNnamtaeFlYZWJqdjlIaVRJCjNQa1h0NisvZHoyMDFTd3RCaU4y
            b0hCT2VwTExXNS8veVJ1cXdIb2lya1kKLS0tIDV1a2FudHh6Y1l2UkhLL1JBSVJx
            YlRiY0xGSTA1M3dRYk1seHVJdS9JOE0KuLlvNKTEOc298eFQPdxRnTkPAevLso5u
            Htp2hfakFQz+b+JZh9vmjZoJsf8R7pR+t9FTaOPK/Bs7ttkTgRG4NA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-13T14:41:53Z"
    mac: ENC[AES256_GCM,data:snkeWkpD7Tek/vN0Z9BILOgAkLXWOy/aHUNzOtxGFo8AvbhIjYKCDUZOHTZ6qf46TLwI+82rxorlRq8JlEkrNsBkh2/JCqbBTB6oM6aPYpv3mJOUttiPguvA2mTaSX6IqDYocc018qqB8CEa42OAM74qWbPSB84prm/XIsiTZSg=,iv:YRe04SLXHhemxt+YJunUDZw84tES9fJCw+eoeBlBiLs=,tag:qdZ/nCQtbEbPMfgaiqAQEQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
