apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:+algh3L/T4nT7p07znWLF+dRv4iBj5cE,iv:KL9rJU5iwqm220imcuZi+3b9QMeA4y7nnOCN9VrsGhs=,tag:2HEDCL8kTmVM20FJskWVZQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xet7mguda7d2gt4f6re7nsv4cdr7tmqeh4lvfyhxeg66sjtghv2q9xd44n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhbkMreEhDYnRlMkMvT1Zm
            TDRUQWdzOWVSODVwZEcwRUlpa2NrMW5kZVQ4CmJJbDZZN0tzV2JqRTI1dno4bUhW
            SDU4aXlZOG56V0p1UnJweVUrbGdiYTQKLS0tIFpRVmlCeHhiWW56cjc2amZJZ3ZQ
            V1hYa0FzbllKdTU3NU1oT2Y1ZkZjTVkKsuTkTYHzA6agrv0zmCz7iafA9nyzEhRL
            Bhk80tkAw3K9hx5u8lux+zh23dtaxNDc9BZWuD9HCtjm7nESxFHp9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-13T15:22:18Z"
    mac: ENC[AES256_GCM,data:EqwGpeSrJNH53eLF9LcyPRcchj7rFDAhpvDZWyOYCH/q4Lt+kc6Bomjd5X1ngtUDbkcR3KXn9204yt0xzohJe3dGqNIrvykGB3TQ95Y5jyiQ0alD3Zs0Upy+0TTa3YJH2I2EvtddoelgtVw0UPfYzfDo10RJqssaAdW6HzCtZkQ=,iv:8YcS8xxxu4VBAY2oRV+XnZcxmnU5YubSQB3ESTe9gwo=,tag:c25GuoZsCi8lXCEbK2fmNg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
