apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:ilQj4JcZuEaVjXK52quZ0Js2K/mDmeR/DYGNxHJJvzRXXK/XM+CszQ==,iv:t5B3kltnjxJWTKYWwlmZ5jLJAiwf84lJOBBd3Yph2lg=,tag:LpMksSWo7KUCZqiFHjDnFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xet7mguda7d2gt4f6re7nsv4cdr7tmqeh4lvfyhxeg66sjtghv2q9xd44n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlWlNhaVZuWGZmcVpFU1Vh
            VXpDZzRiYXZXUmlWT3cwOFJaWmJYT1BLVzFJCkR1ZnpkTGlLWVE4cWlhVDQ1WTQx
            Z040TVIrQTk4Rk9zcDkxcWRIR3NMTjAKLS0tIDg0WHZyM0NpNzZLRTAyTkhWK2Rh
            UDZZK3hvMWlXMWx6aW41NVAxbkdKYXcKODZ+81G3dF60ZV/+RY07HcuuogtG+5qV
            jqrJCYpOC/6DJD4VUW3xANxngrzOLvDonZQpV/pSmKwgNswv8DtQXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-13T14:41:49Z"
    mac: ENC[AES256_GCM,data:dG1DeU/v3lUyW1izqpZOPsOQTGMWZ7I3ESg4El4w/iE2tOU4fPbbuPYBpU4LTwKPpQViGNQYxiGfWG2UzU1Jeq10Kz4IlWhdkjTdcITx+Pr5Lc2bRGa4Y4YM8I58qpecoEzSW8yG8PFebhcPycgIEDkIzVrMcN9/dlMgQlkvM28=,iv:rY8qd1JDvYbc1j5Ld/+/szAzGOMpqFU1RbVg2JbCtHY=,tag:WQ8WKXc9VnCVpmAC2y66sQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
