apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:J0aX9eMO8FS7JklggjlAH3PECj7lw7gXRUrQYCPOTl/ss8fVn8cUbg==,iv:rtg+jZWEOK/nUN99faMEzRzXfKz+5/Vo/XqXYaKOigQ=,tag:YUHWWeIGdCI+2hZU+5aKWg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xet7mguda7d2gt4f6re7nsv4cdr7tmqeh4lvfyhxeg66sjtghv2q9xd44n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZdXpDTXFBRk1tRlE2N0gz
            S08yWnA2NDR4MTVVbm1Bc2ZJeTFKaUtUdEFjCkZRdU93M0Z3aU1MeTlHM2R2KzJt
            MjlVeVVhYUN3a041VUFqa0JsUnZ5TncKLS0tICs5R3VPTlVHZHYyY3FzWTVkQUph
            cjAzRHdTOXZvYTBhQmhzQldWWWpmb1EK+iM1XuywJGaK2gczAAI/by9mXEVBH54r
            d095Apt0dT4sd3GoSTceMEakAWTLCEKO0+SxcCucrer0LAQFaCSsJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-13T15:22:18Z"
    mac: ENC[AES256_GCM,data:7+71N9vHPGaq6xnnSNg1/F+mJXAFu0/93NNkiHq3M1cp1d7qnIWxT0tVgaMPSOX4SGV0XhiGMMPA9kN11ZrLMVi8XkimQXJO7ugMPTvtqWMTzGBnS9CFqeiL5xO4/In/qRNv9br3QUZsaaYNWjf1QrWW6kbBckSSr3WTEBGrwvU=,iv:r7QTqinSApVjdcrXwr0h85g7Kr4vKO1fEYSNH6SkQ9o=,tag:qs7fXFrnKruFrZHa9tNDKg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
