apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:mFCFd8fOZIWQtBseGsYb/05ibemqUggWAHnAVVnRsE5Jp/5D,iv:A/ln/QKkmsY3JlRG2pm00ltZNDQ3QpoxdraR+EHfup4=,tag:rgbgAky64NAU+RPofbHxyQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:213UBAWIgCX/NvqnEUooiaRlIcVImdkve49dpglhheNaU7WAme0jPW7aH4V+L/Wu4DJCLM1/Jje5FAonAMEruhpDSZn4uljmoJTSiMNh9EMB/iVpdggONnHXoZuTId16M/GgAdeyeAckgUztbEtOHfbYW1NNEcRtS7Za2vdkv5U3Q/QXvV/NTDrBQVPmwCD5x4c7Hnbhtd4U9BpJo3tzGu5a81nQhI+wY45M6KLb7A==,iv:3ejNSble7QbFMInOHQemHKmX27OQctTG9lhn1WbY1Q8=,tag:XCxC0/yruWN/HxvvUS3zHw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xet7mguda7d2gt4f6re7nsv4cdr7tmqeh4lvfyhxeg66sjtghv2q9xd44n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIUjkwQzZhTjd4eXBHUndH
            NkRpdFdyNmlHZGJSR255RUYzVERSd2FmeVI4ClRiS1dDbG80alJXeHBibkc1WEhq
            Q3RLMkxXdGswcEI0UUFFelFDWjVHR1kKLS0tIE5IWnA1NkJMcFZuOS80U2pRbUcy
            QVhOdXVoL1NzV1RIZzRMd3hUWEd5cDgKmmE8qZ1LJNuzamnsR9F9BbCMEJpi8t6V
            s7ScOodHa/PSvnT/KppdZk9fjBCPmpOncy9ASPIllhpMIQ7gLxhQLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-15T15:47:48Z"
    mac: ENC[AES256_GCM,data:H/sUHFCv9/w+yPip0Slu82yR0Bg3/9z+C4hZI/uUfmqKqci1Sx3+RZzJzaOzqPKk6m5HL/PAikhdkQr35R+mxobnNtSGkywrctN6Anh5/TYSQ/f0CL1T80lcgixvX/7BAEFgg3jmeGywUVR7dA/60Q7OEvir05daWimbt1kFcDw=,iv:7y65LD0tJHorB+ilqgvNrZdcYFPkEutaqyAsxMYp5T0=,tag:ZLEbICaFOjnxjJJ9Gjbcjw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
