---
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: "${APP}"
spec:
  postgresVersion: 15
  dataSource:
    pgbackrest:
      stanza: db
      global:
        repo1-path: "/${APP}/repo1"
        repo1-s3-uri-style: path
      repo:
        name: repo1
        s3:
          bucket: "crunchy-postgres"
          endpoint: "192.168.3.174"
          region: "us-east-1"
  patroni:
    dynamicConfiguration:
      synchronous_mode: true
      postgresql:
        synchronous_commit: "on"
        pg_hba:
          - hostnossl all all 10.244.0.0/16 md5
          - hostssl all all all md5
  instances:
    - name: postgres
      replicas: 2
      dataVolumeClaimSpec:
        storageClassName: local-hostpath
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
  users:
    - name: "${DB_USER}"
      databases:
        - "${DB_NAME}"
      options: "SUPERUSER"
      password:
        type: AlphaNumeric
  backups:
    pgbackrest:
      global:
        archive-push-queue-max: 4GiB
        repo1-retention-full: "14"
        repo1-retention-full-type: time
        repo1-path: "/${APP}/repo1"
        repo1-s3-uri-style: path
      manual:
        repoName: repo1
        options:
          - --type=full
      repos:
        - name: repo1
          schedules:
            full: "0 1 * * 0"
            differential: "0 1 * * 1-6"
          s3:
            bucket: "crunchy-postgres"
            endpoint: "192.168.3.174"
            region: "us-east-1"
