apiVersion: v1
data:
    SECRET_KEY_BASE: ENC[AES256_GCM,data:pv1FMsguSOxiYuVM9n4ptN7K8aiHUistTxHeI3JeT7eO0pIBLIPXcdqqbYTxOd1/OnIbfi4kggQNhhXvwDjMsPkLSzE2GBte6biatn8ltsDnQtVS6HvGMQ==,iv:VRvVLLCnCf50t0soOjvEZctyfGdN7MZhO8EG2oS3av0=,tag:bs6739SyFgLPeunGeMbswA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: phoenix-app
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xet7mguda7d2gt4f6re7nsv4cdr7tmqeh4lvfyhxeg66sjtghv2q9xd44n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwVElqUHZrNjRsOTJTR2pE
            dDl1YjFubU9NOFA2VStabXMvQ0lDV3lYelZZCi95a2wyQkFLVC9SenRpeEFtdFl4
            Z1BraEhCSlRpa01IaGNMT0F4b0w5NE0KLS0tIElyVzllR0tIU3hOSFNSM1g0eFhR
            UHVZL1pONHl4NWlCRmxjcHRZalRiYWMK/IZThhMcrUjuVoabDuodDyceXVbfenMY
            +P3GtApd2r7yani7dxcdbNiTsf57aRQjKL6o/OHfe7wHzRZuP/rHdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-13T23:58:11Z"
    mac: ENC[AES256_GCM,data:2u0fEIiGF8ZqFodcG+UesyRaJrcG3WKLGfvRG61BB+VWaGlYcmSqQ1swHxOR+PNH4GxYh5dE9ClsSHsR+AXkswbZpLM9zWhHvy17zF1k0JhdTkosmsc/816vFvPF3TqpHmb6cJa/R42ZK505kR1et88VfPnjf2wvkGD6gXj3H2c=,iv:tfhld9JURvbu7V5zRT0CbMeMH8+0F83Sfg59LKAuWcg=,tag:a+U8lUjpapjOkfRYyZHPYA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
